# Generated by Django 4.1.1 on 2022-09-08 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=255)),
                ('arrive', models.CharField(max_length=255)),
                ('montant', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Vol',
                'ordering': ['id', 'depart', 'arrive', 'montant'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.vol')),
            ],
            options={
                'verbose_name': 'Reservation',
                'ordering': ['id', 'vol', 'user', 'date'],
            },
        ),
    ]
