# Generated by Django 4.1.1 on 2022-09-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_reservation_retour_inclut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id', 'vol', 'user', 'montant', 'date_depart', 'date_retour'], 'verbose_name': 'Reservation'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_depart',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_retour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vol',
            name='arrive',
            field=models.CharField(choices=[('CDG', 'CDG'), ('FJK', 'FJK'), ('DTW', 'DTW')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vol',
            name='depart',
            field=models.CharField(choices=[('CDG', 'CDG'), ('FJK', 'FJK'), ('DTW', 'DTW')], max_length=255),
        ),
    ]
