# Generated by Django 4.1.1 on 2022-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_reservation_options_reservation_champagne'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id', 'nom', 'prenom', 'vol', 'user', 'montant', 'champagne', 'date_depart', 'date_retour'], 'verbose_name': 'Reservation'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='nb_place',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom',
            field=models.CharField(default='booking', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='prenom',
            field=models.CharField(default='booking', max_length=255),
            preserve_default=False,
        ),
    ]
