<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-09 12:55
=======
# Generated by Django 4.1.1 on 2022-09-09 13:14
>>>>>>> c2ff775 (save)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('booking_app', '0006_alter_reservation_options_reservation_nb_place_and_more'),
=======
        ("booking_app", "0006_alter_reservation_options_reservation_nb_place_and_more"),
>>>>>>> c2ff775 (save)
    ]

    operations = [
        migrations.AlterModelOptions(
<<<<<<< HEAD
            name='reservation',
            options={'ordering': ['id', 'nom', 'prenom', 'nb_place', 'vol', 'montant', 'champagne', 'date_depart', 'date_retour'], 'verbose_name': 'Reservation'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
=======
            name="reservation",
            options={
                "ordering": [
                    "id",
                    "nom",
                    "prenom",
                    "nb_place",
                    "vol",
                    "montant",
                    "champagne",
                    "date_depart",
                    "date_retour",
                ],
                "verbose_name": "Reservation",
            },
        ),
        migrations.RemoveField(model_name="reservation", name="user",),
>>>>>>> c2ff775 (save)
    ]
