# Generated by Django 4.1.1 on 2022-09-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_vol_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id', 'nom', 'prenom', 'nb_place', 'vol', 'montant', 'champagne', 'first_class', 'date_depart', 'date_retour'], 'verbose_name': 'Reservation'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_class',
            field=models.BooleanField(default=False),
        ),
    ]
