# Generated by Django 4.1.1 on 2022-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0009_alter_reservation_options_reservation_first_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['id', 'nom', 'prenom', 'nb_place', 'vol', 'montant', 'champagne', 'first_class', 'currency', 'date_depart', 'date_retour'], 'verbose_name': 'Reservation'},
        ),
        migrations.AddField(
            model_name='reservation',
            name='currency',
            field=models.CharField(choices=[('EURO', 'EURO'), ('DOLLAR', 'DOLLAR')], default='EURO', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vol',
            name='arrive',
            field=models.CharField(choices=[('CDG', 'CDG'), ('FJK', 'FJK'), ('LAD', 'LAD'), ('DTW', 'DTW')], max_length=255),
        ),
        migrations.AlterField(
            model_name='vol',
            name='depart',
            field=models.CharField(choices=[('CDG', 'CDG'), ('FJK', 'FJK'), ('LAD', 'LAD'), ('DTW', 'DTW')], max_length=255),
        ),
    ]
