# Generated by Django 4.1.1 on 2022-09-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("booking_app", "0010_alter_reservation_options_reservation_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255, null=True)),
                ("nom", models.CharField(max_length=255, null=True)),
                (
                    "depart",
                    models.CharField(
                        choices=[
                            ("CDG", "CDG"),
                            ("JFK", "JFK"),
                            ("EWR", "EWR"),
                            ("ORD", "ORD"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "arrive",
                    models.CharField(
                        choices=[
                            ("CDG", "CDG"),
                            ("JFK", "JFK"),
                            ("EWR", "EWR"),
                            ("ORD", "ORD"),
                        ],
                        max_length=255,
                    ),
                ),
                ("montant", models.IntegerField()),
                ("places", models.IntegerField()),
            ],
            options={
                "verbose_name": "Train",
                "ordering": ["id", "nom", "depart", "arrive", "montant"],
            },
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": [
                    "id",
                    "nom",
                    "prenom",
                    "nb_place",
                    "transport",
                    "montant",
                    "champagne",
                    "first_class",
                    "currency",
                    "date_depart",
                    "date_retour",
                ],
                "verbose_name": "Reservation",
            },
        ),
        migrations.AlterModelOptions(
            name="vol",
            options={
                "ordering": ["id", "nom", "depart", "arrive", "montant"],
                "verbose_name": "Vol",
            },
        ),
        migrations.RemoveField(model_name="reservation", name="vol",),
        migrations.AddField(
            model_name="reservation",
            name="content_type",
            field=models.ForeignKey(
                default=8,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="transport",
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vol",
            name="nom",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="vol",
            name="arrive",
            field=models.CharField(
                choices=[
                    ("CDG", "CDG"),
                    ("JFK", "JFK"),
                    ("LAD", "LAD"),
                    ("DTW", "DTW"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="vol",
            name="depart",
            field=models.CharField(
                choices=[
                    ("CDG", "CDG"),
                    ("JFK", "JFK"),
                    ("LAD", "LAD"),
                    ("DTW", "DTW"),
                ],
                max_length=255,
            ),
        ),
    ]
